// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBjcoCpYky97dInhaY6nCvfjT6EufGmd8',
    appId: '1:8864383414:web:073ea4498447e3b3168117',
    messagingSenderId: '8864383414',
    projectId: 'litcon-blog',
    authDomain: 'litcon-blog.firebaseapp.com',
    storageBucket: 'litcon-blog.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtnMvNxh1rBo6sEuD0UATzcmkcquSfvfY',
    appId: '1:8864383414:android:1d96b6e1cb380f28168117',
    messagingSenderId: '8864383414',
    projectId: 'litcon-blog',
    storageBucket: 'litcon-blog.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlEi7AGDStluHM0GJNDWvl1meYTKMEqLY',
    appId: '1:8864383414:ios:0b9a4702eaade338168117',
    messagingSenderId: '8864383414',
    projectId: 'litcon-blog',
    storageBucket: 'litcon-blog.appspot.com',
    iosClientId: '8864383414-rs2s6af2sek17qksmo02tbogl5s50mh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.litcon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlEi7AGDStluHM0GJNDWvl1meYTKMEqLY',
    appId: '1:8864383414:ios:0b9a4702eaade338168117',
    messagingSenderId: '8864383414',
    projectId: 'litcon-blog',
    storageBucket: 'litcon-blog.appspot.com',
    iosClientId: '8864383414-rs2s6af2sek17qksmo02tbogl5s50mh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.litcon',
  );
}
